name: Pylint

on: [push]
# push:
#     branches:
#         - 'feat/**'
#         - $default-branch
#   pull_request:
#     branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python --version
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true
  check-mock:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python --version
    - name: Initiating mock setup
      run: |
        SCRIPTPATH=$($(pwd)/k8s_labeling/generate_configmap_mock.sh)
        alias kubectl="/bin/bash ./k8s_labeling/generate_configmap_mock.sh"
        pwd && ls -la ./ && ls -lha $SCRIPTPATH
        alias
        shopt -s expand_aliases
        kubectl get configmap
    #   continue-on-error: true
