name: Pylint

on: [push]
# push:
#     branches:
#         - 'feat/**'
#         - $default-branch
#   pull_request:
#     branches: [ $default-branch ]

jobs:
  k8s-labeling-ci-build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python --version
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true
    - name: Initiating mock setup
      run: |
        set +x
        alias kubectl="/bin/bash ./k8s_labeling/generate_configmap_mock.sh"
        alias
        shopt -s expand_aliases
        kubectl get configmap
    #   continue-on-error: true
    - name: Run bash script
      run: |
        cd ./k8s_labeling && /bin/bash action_targeting.sh
    #   continue-on-error: true
    - name: Run Yara python script
      run: |
        cd ./k8s_labeling && python action_targeting_yarachek.py
      continue-on-error: true
    - name: Run Gruzchik python script
      run: |
        cd ./k8s_labeling && python action_targeting_gruchik.py
      continue-on-error: true